layui.define(function (exports) {
    var lang = {
        en: {  //Log Out
            "title": "Transaction",
            "market": "Market",
            "price": "Price",
            "delta": "Rise",
            "high": "High",
            "low": "Low",
            "volume": "Total",
            "count": "Total",
            "size": "Quantity",
            "total": "Cumulative",
            "date": "Time",
            "type": "Type",
            "buy": "Buy",
            "sell": "Sell",
            "num_remaining": "Remaining Quantity",
            "action": "Action",
            "status": "Status",
            "innovation_zone": "Innovation Zone",
            "transaction_history": "Transaction History",
            "limit_price": "Limiting Price",
            "market_price": "Market Price",
            "property": "Asset",
            "submitted":"Transaction Struck",
            "average_price":"Average Price",
            "img-sell-buy":"Sell/Buy",
            "img-sell":"Sell",
            "img-buy":"Buy",
            "current-entrust":"Current Entrustment",
            "history-entrust":"Historical Entrustment",
            "suspended":"Suspended",
            "no_data":"No Data",
            "history_entrust_status": {
                0: 'Entrusting...',
                1: 'Entrustment Successful',
                2: 'Partial Transaction',
                3: 'Transaction Struck',
                4: 'On-Floor Order Cancellation',
                5: 'Out-of-Floor Order Cancellation',
            },
            "error_code": {
                3009: 'Account balance is insufficient!',
                3013: 'Oder failed!',
            },
            "user_center": {
                "real_name_yes": "Real Name Authentication",
                "real_name_no": "No Real Name Authentication",
                "account_information": "Account Information",
                "identity_auth": "Identity Authentication",
                "rec_center": "RECOM Center",
                "assets_manage": "Asset Management",
                "entrusted_manage": "Entrusted Management",
                "login": "Log In",
                "register": "Register",
                "logout": "Log Out",
            },
            "head_drop_down": {
                "market": "Market",
                "latest_deal": "Latest Transaction Value",
                "up_down_24h": "24h Rise/Fall",
                "turnover_24h": "24h Turnover",
            },
            "trading": {
                "coin_not_exist": "Currency does not exist!",
                "unauthenticated": "No Real Name Authentication!",
                "please_input_buy_price": "Please enter buying price!",
                "buy_num_not_empty": "Purchasing quantity cannot be void!",
                "buy_submit_success": "Buying application successfully submitted!",
                "please_input_sell_price": "Please enter selling price!",
                "sell_submit_success": "Selling application successfully submitted!",
                "sell_num_not_empty": "Selling quantity cannot be void!",
                "account_balance_insufficient": "Account balance is insufficient!",
                "price_not_empty": "Price cannot be void",
                "buy_error": "Buy failed. Please try later!",
            },
            "network_anomaly": "Network Anomaly",
            "timeSharing":"Time Sharing",
            "weeks":"Weeks",
            "indicators":"Indicators",
        },
        zh_TW: {  //退出登录
            "title": "交易",
            "market": "市場",
            "price": "價格",
            "delta": "漲幅",
            "high": "最高",
            "low": "最低",
            "volume": "總量",
            "count": "总计",
            "size": "數量",
            "total": "累積",
            "date": "時間",
            "type": "類型",
            "buy": "買入",
            "sell": "賣出",
            "num_remaining": "剩余數量",
            "action": "操作",
            "status": "狀態",
            "innovation_zone": "創新區",
            "transaction_history": "交易歷史",
            "limit_price": "限價",
            "market_price": "市價",
            "property": "資產",
            "submitted":"已成交",
            "average_price":"均價",
            "img-sell-buy":"賣出/買入",
            "img-sell":"賣出",
            "img-buy":"買入",
            "current-entrust":"當前委托",
            "history-entrust":"歷史委托",
            "suspended":"停　盤",
            "no_data":"無數據",
            "history_entrust_status": {
                0: '委托中',
                1: '委托成功',
                2: '部分成交',
                3: '已成交',
                4: '場內撤單',
                5: '場外撤單',
            },
            "error_code": {
                3009: '賬戶余額不足！',
                3013: '下单失败！',
            },
            "user_center": {
                "real_name_yes": "已實名認證",
                "real_name_no": "未實名認證",
                "account_information": "賬戶信息",
                "identity_auth": "身份認證",
                "rec_center": "推薦中心",
                "assets_manage": "資產管理",
                "entrusted_manage": "委托管理",
                "login": "登　錄",
                "register": "註　冊",
                "logout": "退出",
            },
            "head_drop_down": {
                "market": "市場",
                "latest_deal": "最新成交值",
                "up_down_24h": "24小時漲跌幅",
                "turnover_24h": "24小時成交量",
            },
            "trading": {
                "coin_not_exist": "幣種不存在！",
                "unauthenticated": "未实名认证!",
                "please_input_buy_price": "請輸入買入價格！",
                "buy_num_not_empty": "購買數量不能為空！",
                "buy_submit_success": "買入申請提交成功！",
                "please_input_sell_price": "請輸入賣出價格！",
                "sell_submit_success": "賣出申請提交成功！",
                "sell_num_not_empty": "賣出數量不能為空！",
                "account_balance_insufficient": "賬戶余額不足！",
                "price_not_empty": "價格不能為空",
                "buy_error": "購買失敗稍後重試！",
            },
            "network_anomaly": "網絡異常",
            "timeSharing":"分時",
            "weeks":"周",
            "indicators":"指標",
        },
        zh: {  //退出登录
            "title": "交易",
            "market": "市场",
            "price": "价格",
            "delta": "涨幅",
            "high": "最高",
            "low": "最低",
            "volume": "总量",
            "count": "总计",
            "size": "数量",
            "total": "累积",
            "date": "时间",
            "type": "类型",
            "buy": "买入",
            "sell": "卖出",
            "num_remaining": "剩余数量",
            "action": "操作",
            "status": "状态",
            "innovation_zone": "创新区",
            "transaction_history": "交易历史",
            "limit_price": "限价",
            "market_price": "市价",
            "property": "资产",
            "submitted":"已成交",
            "average_price":"均价",
            "img-sell-buy":"卖出/买入",
            "img-sell":"卖出",
            "img-buy":"买入",
            "current-entrust":"当前委托",
            "history-entrust":"历史委托",
            "suspended":"停　盘",
            "no_data":"无数据",
            "history_entrust_status": {
                0: '委托中',
                1: '委托成功',
                2: '部分成交',
                3: '已成交',
                4: '场内撤单',
                5: '场外撤单',
            },
            "error_code": {
                3009: '账户余额不足！'
            },
            "user_center": {
                "real_name_yes": "已实名认证",
                "real_name_no": "未实名认证",
                "account_information": "账户信息",
                "identity_auth": "身份认证",
                "rec_center": "推荐中心",
                "assets_manage": "资产管理",
                "entrusted_manage": "委托管理",
                "login": "登　录",
                "register": "注　册",
                "logout": "退出",
            },
            "head_drop_down": {
                "market": "市场",
                "latest_deal": "最新成交值",
                "up_down_24h": "24小时涨跌幅",
                "turnover_24h": "24小时成交量",
            },
            "trading": {
                "coin_not_exist": "币种不存在！",
                "unauthenticated": "未实名认证!",
                "please_input_buy_price": "请输入买入价格！",
                "buy_num_not_empty": "购买数量不能为空！",
                "buy_submit_success": "买入申请提交成功！",
                "please_input_sell_price": "请输入卖出价格！",
                "sell_submit_success": "卖出申请提交成功！",
                "sell_num_not_empty": "卖出数量不能为空！",
                "account_balance_insufficient": "账户余额不足！",
                "price_not_empty": "价格不能为空",
                "buy_error": "购买失败稍后重试！",
            },
            "network_anomaly": "网络异常",
            "timeSharing":"分时",
            "weeks":"周",
            "indicators":"指标",
        },
    };
    //console.log(lang.zh_TW);
    exports('lang', lang);
});